import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

// Routes to pre-render
const routes = [
  '/',
  '/about',
  '/products',
  '/quote',
  '/contact',
  '/product/mono-cartons',
  '/product/rigid-boxes',
  '/product/corrugated-boxes',
  '/product/pouches',
  '/product/cold-seal-blisters',
  '/product/hot-seal-blisters',
  '/product/self-adhesive-labels',
  '/product/canister-boxes',
  '/product/promotional-tape-roll'
];

async function prerender() {
  console.log('Starting pre-rendering...');

  // The template generated by client build
  const template = await fs.readFile(path.resolve(__dirname, 'dist/index.html'), 'utf-8');

  // The render function generated by server build
  // We use path.join and import() to correctly load the module
  const serverEntryPath = path.resolve(__dirname, 'dist-ssr/entry-server.js');
  const { render } = await import(`file://${serverEntryPath}`);

  for (const url of routes) {
    const helmetContext: any = {};
    
    // Render the React app to HTML string
    const appHtml = render(url, helmetContext);
    
    // Extract helmet tags
    const { helmet } = helmetContext;
    const helmetTags = helmet ? `
      ${helmet.title.toString()}
      ${helmet.priority.toString()}
      ${helmet.meta.toString()}
      ${helmet.link.toString()}
      ${helmet.script.toString()}
    ` : '';

    // Inject helmet tags into <head> and app HTML into <div id="root">
    const html = template
      .replace('<!--ssr-head-->', helmetTags)
      .replace('</head>', `${helmetTags}</head>`) // Fallback if no ssr-head comment
      .replace('<div id="root"></div>', `<div id="root">${appHtml}</div>`);

    // Determine file path
    const isIndex = url === '/';
    const filePath = isIndex 
      ? path.resolve(__dirname, 'dist/index.html') 
      : path.resolve(__dirname, `dist${url}.html`); // e.g. dist/about.html

    const dir = path.dirname(filePath);
    await fs.mkdir(dir, { recursive: true });
    await fs.writeFile(filePath, html);

    // Also write to dist/route/index.html to support Vercel clean URLs seamlessly if needed,
    // though vercel.json rewrites or trailingSlash configuration usually handles this.
    // Let's create both just in case, but Vercel prefers /about.html or /about/index.html.
    if (!isIndex) {
      const indexFilePath = path.resolve(__dirname, `dist${url}/index.html`);
      await fs.mkdir(path.dirname(indexFilePath), { recursive: true });
      await fs.writeFile(indexFilePath, html);
    }

    console.log(`pre-rendered ${url}`);
  }
  console.log('Pre-rendering complete.');
}

prerender().catch((err) => {
  console.error('Error during pre-rendering:', err);
  process.exit(1);
});
